export default [
  {
    name: 'BCH',
    aclass: 'currency',
    altname: 'BCH',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'DASH',
    aclass: 'currency',
    altname: 'DASH',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'EOS',
    aclass: 'currency',
    altname: 'EOS',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'GNO',
    aclass: 'currency',
    altname: 'GNO',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'KFEE',
    aclass: 'currency',
    altname: 'FEE',
    decimals: 2,
    displayDecimals: 2,
  },
  {
    name: 'USDT',
    aclass: 'currency',
    altname: 'USDT',
    decimals: 8,
    displayDecimals: 4,
  },
  {
    name: 'XDAO',
    aclass: 'currency',
    altname: 'DAO',
    decimals: 10,
    displayDecimals: 3,
  },
  {
    name: 'XETC',
    aclass: 'currency',
    altname: 'ETC',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XETH',
    aclass: 'currency',
    altname: 'ETH',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XICN',
    aclass: 'currency',
    altname: 'ICN',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XLTC',
    aclass: 'currency',
    altname: 'LTC',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XMLN',
    aclass: 'currency',
    altname: 'MLN',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XNMC',
    aclass: 'currency',
    altname: 'NMC',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XREP',
    aclass: 'currency',
    altname: 'REP',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XXBT',
    aclass: 'currency',
    altname: 'XBT',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XXDG',
    aclass: 'currency',
    altname: 'XDG',
    decimals: 8,
    displayDecimals: 2,
  },
  {
    name: 'XXLM',
    aclass: 'currency',
    altname: 'XLM',
    decimals: 8,
    displayDecimals: 5,
  },
  {
    name: 'XXMR',
    aclass: 'currency',
    altname: 'XMR',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'XXRP',
    aclass: 'currency',
    altname: 'XRP',
    decimals: 8,
    displayDecimals: 5,
  },
  {
    name: 'XXVN',
    aclass: 'currency',
    altname: 'XVN',
    decimals: 4,
    displayDecimals: 2,
  },
  {
    name: 'XZEC',
    aclass: 'currency',
    altname: 'ZEC',
    decimals: 10,
    displayDecimals: 5,
  },
  {
    name: 'ZCAD',
    aclass: 'currency',
    altname: 'CAD',
    decimals: 4,
    displayDecimals: 2,
  },
  {
    name: 'ZEUR',
    aclass: 'currency',
    altname: 'EUR',
    decimals: 4,
    displayDecimals: 2,
  },
  {
    name: 'ZGBP',
    aclass: 'currency',
    altname: 'GBP',
    decimals: 4,
    displayDecimals: 2,
  },
  {
    name: 'ZJPY',
    aclass: 'currency',
    altname: 'JPY',
    decimals: 2,
    displayDecimals: 0,
  },
  {
    name: 'ZKRW',
    aclass: 'currency',
    altname: 'KRW',
    decimals: 2,
    displayDecimals: 0,
  },
  {
    name: 'ZUSD',
    aclass: 'currency',
    altname: 'USD',
    decimals: 4,
    displayDecimals: 2,
  },
];
